// Quality presets, persisted user settings and the (ja / en) strings.
const KEY = 'enoden-walk.settings.v1';

// bump/ssao/dof/motionBlur are new (ultra-only) effects; smaa/atmos gate the shared postprocess passes (see render.js).
// atmos mirrors the old implicit bloom||msaa gate exactly, so low/medium/high keep their pre-existing look untouched;
// smaa (edge antialiasing) and the chromatic-aberration/grain pass are cheap enough to run on every preset instead.
export const PRESETS = {
  low: { dpr: 1.0, shadow: 1024, shadowRange: 34, bloom: false, msaa: 0, leafCards: false, detail: 0, clouds: false, wind: false, pointLights: 1, seaDepth: false, glow: true, bump: false, ssao: false, dof: false, motionBlur: false, smaa: true, atmos: false, waves: false, flutter: false, skyPhysical: false },
  medium: { dpr: 1.25, shadow: 2048, shadowRange: 50, bloom: true, msaa: 0, leafCards: true, detail: 1, clouds: true, wind: true, pointLights: 2, seaDepth: true, glow: true, bump: false, ssao: false, dof: false, motionBlur: false, smaa: true, atmos: true, waves: false, flutter: false, skyPhysical: false },
  high: { dpr: 1.75, shadow: 4096, shadowRange: 70, bloom: true, msaa: 4, leafCards: true, detail: 2, clouds: true, wind: true, pointLights: 4, seaDepth: true, glow: true, bump: false, ssao: false, dof: false, motionBlur: false, smaa: true, atmos: true, waves: false, flutter: false, skyPhysical: false },
  // charShadow (C5.3): a real second shadow-only light would double-light the character in three.js's standard
  // pipeline (there is no per-object "light layer" exclusion for illumination, only for shadow-map culling), so
  // this doubles the shared shadow map's resolution instead (8192 vs 4096) — same "crisper self-shadow" result,
  // without the risk of a visible brightness seam around the character.
  ultra: { dpr: 1.75, shadow: 8192, shadowRange: 70, bloom: true, msaa: 4, leafCards: true, detail: 2, clouds: true, wind: true, pointLights: 4, seaDepth: true, glow: true, bump: true, ssao: true, dof: true, motionBlur: true, smaa: true, atmos: true, waves: true, flutter: true, skyPhysical: true },
};

export const DEFAULTS = {
  quality: 'high', // auto | low | medium | high
  time: 'dusk', // day | dusk | night
  volume: 0.8,
  muted: false,
  lang: /^ja/i.test(navigator.language || 'ja') ? 'ja' : 'en',
  sens: 1.0,
  invertY: false,
  viewMode: 'drag', // drag | right | lock
  autoCam: true,
  fps: false,
  announce: true, // spoken station announcements (Web Speech API)
  autoTime: false, // day -> dusk -> night cycle
  rain: false,
  motionBlur: false, // ultra quality only; off by default even there (motion-sickness risk)
  reduceMotion: typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches,
  handed: 'right', // right | left — which side the touch move-stick sits on
};

export function loadSettings() {
  let s = {};
  try {
    s = JSON.parse(localStorage.getItem(KEY) || '{}');
  } catch {
    s = {};
  }
  return { ...DEFAULTS, ...s };
}

export function saveSettings(s) {
  try {
    localStorage.setItem(KEY, JSON.stringify(s));
  } catch {
    /* private mode: ignore */
  }
}

/** auto preset: touch devices / weak CPUs / slow or data-saver connections start on low, everything else on medium (the frame-time governor adapts the resolution) */
export function autoPreset() {
  const coarse = typeof matchMedia === 'function' && matchMedia('(pointer: coarse)').matches;
  const cores = navigator.hardwareConcurrency || 4;
  const conn = navigator.connection;
  const slowNet = conn && (conn.saveData || /^(slow-2g|2g|3g)$/.test(conn.effectiveType || ''));
  if (coarse || cores <= 4 || slowNet) return 'low';
  return cores >= 12 ? 'high' : 'medium';
}

const STR = {
  ja: {
    title: '江ノ電 鎌倉高校前 散歩',
    subtitle: '夕暮れの1号踏切と、相模湾の見える丘の街を歩こう',
    start: '散歩をはじめる',
    loading: '読み込み中…',
    assembling: '街を組み立て中…',
    ready: '準備できました',
    failed: '読み込みに失敗しました',
    retry: 'もう一度試す',
    nowebgl: 'WebGL に対応したブラウザで開いてください',
    where_default: '鎌倉高校前 周辺',
    where_near: '{name} 付近',
    help: '操作ガイド',
    settings: '設定',
    spots: '名所へ移動',
    photo: '写真モード',
    share: '共有',
    copied: 'リンクをコピーしました',
    close: '閉じる',
    time: '時刻',
    day: '昼',
    dusk: '夕方',
    night: '夜',
    quality: '画質',
    q_auto: '自動',
    q_low: '低',
    q_medium: '中',
    q_high: '高',
    q_ultra: '最高',
    motionBlur: 'モーションブラー',
    volume: '音量',
    mute: 'ミュート',
    sens: '視点の感度',
    invertY: '上下を反転',
    viewMode: '視点操作',
    vm_drag: '左ドラッグ',
    vm_right: '右ドラッグ',
    vm_lock: 'マウス固定（クリックで開始）',
    autoCam: '移動時に自動で背後へ回る',
    fps: 'FPS を表示',
    lang: '言語',
    reduce: '動きを抑える',
    moveKeys: '移動',
    runKey: '走る',
    sprintKey: '全力',
    jumpKey: 'ジャンプ',
    viewKey: '視点',
    boardKey: '乗る / 降りる',
    soundKey: '音',
    photoKey: '写真モード',
    helpKey: 'このガイド',
    recenterKey: '視点を背後へ',
    gamepad: 'ゲームパッド: 左スティック 移動 / 右スティック 視点 / A ジャンプ / RT 走る / X 全力 / Y 乗る',
    touchHint: 'スマホ: 左側をスライドで移動（奥まで倒すと走る）、右側をドラッグで視点、2本指で拡大縮小',
    tutorial_text: 'ここをスライドして歩こう',
    nextTrain: '次の電車',
    east: '藤沢方面',
    west: '鎌倉方面',
    in: 'あと {s} 秒',
    arriving: '駅に到着中',
    dwell: '駅に停車中',
    passing: '通過中',
    boardPrompt: 'E で乗車',
    alightPrompt: 'E で降りる',
    riding: '乗車中',
    boarded: '乗車しました。車窓の景色を楽しもう',
    alighted: 'ホームに降りました',
    alarm: 'カンカンカン… 電車が来ます',
    clearCrossing: '踏切から出てください',
    hit: '電車に注意！ 踏切の外へ戻りました',
    start_msg: '散歩をはじめましょう',
    sound_on: '音: オン',
    sound_off: '音: オフ',
    photoFov: '画角',
    photoHide: '人物を隠す',
    capture: '撮影して保存',
    saved: '写真を保存しました',
    install_hint: 'ホーム画面に追加すると、アプリのようにすぐ開けます',
    install_hint_ios: '共有ボタン →「ホーム画面に追加」で、アプリのようにすぐ開けます',
    install_btn: '追加',
    exitPhoto: '写真モードを終了',
    quality_now: '画質: {q}',
    credit: '地形・建物: 国土交通省 Project PLATEAU（CC BY 4.0）／ 道路・線路: © OpenStreetMap contributors（ODbL）<br>3Dモデル（風景・電車・人物）は Blender で手続き生成した非公式の創作物です。',
    minimap: '地図',
    helpShort: 'WASD 移動 ・ Shift 走る ・ Space ジャンプ ・ E 乗る ・ ？ ガイド',
    north: '北',
    announce: '駅のアナウンス（音声）',
    autoTime: '時刻を自動で進める',
    rain: '雨',
    handed: '利き手（スマホ操作）',
    handed_right: '右手でボタン',
    handed_left: '左手でボタン',
    platform_hint: 'ホームへは西端のスロープから上がれます',
    st_koshigoe: '腰越',
    st_shichiri: '七里ヶ浜',
    st_here: '鎌倉高校前',
    depart_next: '発車します。次は {st}',
    soon_here: 'まもなく {st}',
    say_arriving_east: 'まもなく、藤沢方面行きの電車が到着します。危ないですから、黄色い線の内側でお待ちください',
    say_arriving_west: 'まもなく、鎌倉方面行きの電車が到着します。危ないですから、黄色い線の内側でお待ちください',
    say_depart: '発車します。次は、{st}です',
    say_soon: 'まもなく、{st}に到着します',
    go_platform: 'ホームへ',
    call_train: '電車を呼ぶ',
    train_called: '電車がやって来ます',
    nav_to: '{name} まで {m} m',
    nav_auto: '自動で歩く',
    nav_manual: '手動',
    nav_stop: '案内をやめる',
    nav_arrived: '到着しました',
    nav_none: '道が見つかりませんでした',
    nav_near: '近くまでしか行けません。行ける所まで案内します',
    nav_hold: '踏切が閉まっています。開くまで待ちます',
    nav_lost: '進めなくなったので案内を終了しました',
    nav_manual_now: '自分で歩くので、案内だけ続けます',
    nav_target: '指定した場所',
    guide_btn: '案内',
    map_hint: 'クリック / タップで、そこまで歩きます（長押しで拡大表示）',
    autowalk_on: 'オートウォーク: オン（F か移動キーで解除）',
    autowalk_off: 'オートウォーク: オフ',
    autowalkKey: 'オートウォーク',
    mapKey: 'ミニマップをクリック',
    mapKeyDesc: 'そこまで自動で歩く',
  },
  en: {
    title: 'Enoden Kamakura-Koko-Mae Walk',
    subtitle: 'Stroll around the famous level crossing and the hills above Sagami Bay',
    start: 'Start walking',
    loading: 'Loading…',
    assembling: 'Building the town…',
    ready: 'Ready',
    failed: 'Failed to load',
    retry: 'Try again',
    nowebgl: 'Please open this page in a WebGL capable browser',
    where_default: 'Kamakura-Koko-Mae area',
    where_near: 'Near {name}',
    help: 'Controls',
    settings: 'Settings',
    spots: 'Go to a spot',
    photo: 'Photo mode',
    share: 'Share',
    copied: 'Link copied',
    close: 'Close',
    time: 'Time of day',
    day: 'Day',
    dusk: 'Dusk',
    night: 'Night',
    quality: 'Quality',
    q_auto: 'Auto',
    q_low: 'Low',
    q_medium: 'Medium',
    q_high: 'High',
    q_ultra: 'Ultra',
    motionBlur: 'Motion blur',
    volume: 'Volume',
    mute: 'Mute',
    sens: 'Look sensitivity',
    invertY: 'Invert vertical look',
    viewMode: 'Camera control',
    vm_drag: 'Left drag',
    vm_right: 'Right drag',
    vm_lock: 'Mouse lock (click to start)',
    autoCam: 'Swing behind me when walking',
    fps: 'Show FPS',
    lang: 'Language',
    reduce: 'Reduce motion',
    moveKeys: 'Move',
    runKey: 'Run',
    sprintKey: 'Sprint',
    jumpKey: 'Jump',
    viewKey: 'Look',
    boardKey: 'Board / alight',
    soundKey: 'Sound',
    photoKey: 'Photo mode',
    helpKey: 'This guide',
    recenterKey: 'Camera behind me',
    gamepad: 'Gamepad: left stick move / right stick look / A jump / RT run / X sprint / Y board',
    touchHint: 'Touch: slide on the left to move (push it all the way for a run), drag on the right to look, pinch to zoom',
    tutorial_text: 'Slide here to walk',
    nextTrain: 'Next train',
    east: 'for Fujisawa',
    west: 'for Kamakura',
    in: 'in {s} s',
    arriving: 'arriving',
    dwell: 'stopped at the station',
    passing: 'passing',
    boardPrompt: 'E: board',
    alightPrompt: 'E: get off',
    riding: 'Riding',
    boarded: 'You boarded. Enjoy the view from the window',
    alighted: 'You got off at the platform',
    alarm: 'Ding-ding-ding… a train is coming',
    clearCrossing: 'Please leave the crossing',
    hit: 'Watch out for trains! Moved out of the crossing',
    start_msg: "Let's take a walk",
    sound_on: 'Sound: on',
    sound_off: 'Sound: off',
    photoFov: 'Field of view',
    photoHide: 'Hide the character',
    capture: 'Capture & save',
    saved: 'Photo saved',
    install_hint: 'Add this to your home screen to open it like an app',
    install_hint_ios: 'Tap Share → "Add to Home Screen" to open it like an app',
    install_btn: 'Add',
    exitPhoto: 'Exit photo mode',
    quality_now: 'Quality: {q}',
    credit: 'Terrain & buildings: MLIT Project PLATEAU (CC BY 4.0) / roads & rails: © OpenStreetMap contributors (ODbL)<br>All 3D models (scenery, train, character) are unofficial procedurally generated creations made with Blender.',
    minimap: 'Map',
    helpShort: 'WASD move · Shift run · Space jump · E board · ? guide',
    north: 'N',
    announce: 'Station announcements (voice)',
    autoTime: 'Advance the time of day automatically',
    rain: 'Rain',
    handed: 'Handedness (touch controls)',
    handed_right: 'Buttons on the right',
    handed_left: 'Buttons on the left',
    platform_hint: 'The platform is reached by the ramp at its west end',
    st_koshigoe: 'Koshigoe',
    st_shichiri: 'Shichirigahama',
    st_here: 'Kamakura-Koko-Mae',
    depart_next: 'Departing. Next stop: {st}',
    soon_here: 'Arriving at {st}',
    say_arriving_east: 'A train for Fujisawa is now arriving. Please stand behind the yellow line.',
    say_arriving_west: 'A train for Kamakura is now arriving. Please stand behind the yellow line.',
    say_depart: 'This train is departing. The next stop is {st}.',
    say_soon: 'We will soon arrive at {st}.',
    go_platform: 'To the platform',
    call_train: 'Call a train',
    train_called: 'A train is on its way',
    nav_to: '{name}: {m} m',
    nav_auto: 'Walk for me',
    nav_manual: 'Manual',
    nav_stop: 'Stop guiding',
    nav_arrived: 'You have arrived',
    nav_none: 'No route found',
    nav_near: 'That place is out of reach. Guiding you as close as possible',
    nav_hold: 'The crossing is closed. Waiting for it to open',
    nav_lost: 'Got stuck, guidance ended',
    nav_manual_now: 'You are walking yourself; guidance continues',
    nav_target: 'Selected spot',
    guide_btn: 'Guide',
    map_hint: 'Click / tap to walk there (long-press to enlarge)',
    autowalk_on: 'Auto-walk: on (F or a move key stops it)',
    autowalk_off: 'Auto-walk: off',
    autowalkKey: 'Auto-walk',
    mapKey: 'Click the minimap',
    mapKeyDesc: 'Walk there automatically',
  },
};

export function makeT(getLang) {
  return (key, vars) => {
    let s = (STR[getLang()] && STR[getLang()][key]) || STR.ja[key] || key;
    if (vars) for (const k in vars) s = s.replace(`{${k}}`, vars[k]);
    return s;
  };
}
